VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "clsMyDListado"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

Public Property Get table() As String

    table = "listado"

End Property

Public Property Get c1() As String

    c1 = "c1"

End Property

Public Property Get c1_t() As String

    c1_t = "listado.c1"

End Property

Public Property Get c2() As String

    c2 = "c2"

End Property

Public Property Get c2_t() As String

    c2_t = "listado.c2"

End Property

Public Property Get c3() As String

    c3 = "c3"

End Property

Public Property Get c3_t() As String

    c3_t = "listado.c3"

End Property

Public Property Get c4() As String

    c4 = "c4"

End Property

Public Property Get c4_t() As String

    c4_t = "listado.c4"

End Property

Public Property Get c5() As String

    c5 = "c5"

End Property

Public Property Get c5_t() As String

    c5_t = "listado.c5"

End Property

Public Property Get c6() As String

    c6 = "c6"

End Property

Public Property Get c6_t() As String

    c6_t = "listado.c6"

End Property

Public Property Get n1() As String

    n1 = "n1"

End Property

Public Property Get n1_t() As String

    n1_t = "listado.n1"

End Property

Public Property Get n2() As String

    n2 = "n2"

End Property

Public Property Get n2_t() As String

    n2_t = "listado.n2"

End Property

Public Property Get n3() As String

    n3 = "n3"

End Property

Public Property Get n3_t() As String

    n3_t = "listado.n3"

End Property

Public Property Get n4() As String

    n4 = "n4"

End Property

Public Property Get n4_t() As String

    n4_t = "listado.n4"

End Property

Public Property Get n5() As String

    n5 = "n5"

End Property

Public Property Get n5_t() As String

    n5_t = "listado.n5"

End Property

Public Property Get n6() As String

    n6 = "n6"

End Property

Public Property Get n6_t() As String

    n6_t = "listado.n6"

End Property

Public Property Get autoID() As String

    autoID = "auto_id"

End Property

Public Property Get autoID_t() As String

    autoID_t = "listado.auto_id"

End Property

Public Property Get created() As String

    created = "created"

End Property

Public Property Get created_t() As String

    created_t = "listado.created"

End Property

